apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: cache-data
          mountPath: /data
      volumes:
      - name: cache-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app: cache
  ports:
  - port: 6379
    targetPort: 6379
