apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-docker-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-active
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-active
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  - port: 443
    targetPort: 443
    nodePort: 30443
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
