apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  password: c3VwZXJzZWNyZXQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-password
type: Opaque
data:
  password: YWRtaW4xMjM=
