apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: my-docker-app
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:7
            command:
            - /bin/bash
            - -c
            - |
              mongodump --host db:27017 --out /backup/$(date +%Y%m%d-%H%M%S)
              aws s3 sync /backup/ s3://my-docker-app-backups/mongodb/
              find /backup -type d -mtime +7 -exec rm -rf {} +
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: mongodb-backup-pvc
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
  namespace: my-docker-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi