apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-docker-app
  namespace: argocd
spec:
  project: my-docker-app
  source:
    repoURL: https://github.com/your-username/my-docker-app
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: my-docker-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true